#!/usr/bin/env node
// 全局模式
var argv = require('yargs')
  .option('n', {
    alias: 'name',
    demand: true,
    default: 'tom',
    describe: 'your name',
    type: 'string'
  })
  .argv;
  

console.log('hello', argv)
console.log('hello', argv.n)
